GET http://localhost:4000/users HTTP/1.1

###

POST http://localhost:4000/users HTTP/1.1
Content-Type: application/json

{
    "nombre": "Valerie",
    "apellido": "Camejo",
    "edad": 35,
    "email": "valerie260492@gmail.com"
}